json.id product.id
json.name product.name
json.price number_to_currency(product.price)
json.images product.images
json.description product.description
json.created_at product.created_at
json.updated_at product.updated_at
json.tax product.tax
json.total product.total
json.is_discounted? product.is_discounted?
json.supplier product.supplier
